### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by Darkproduct**
- Provide the real dependencies in the package.xml
- Add license to package.xml
- Create models and launch folder (error if not existent)
- Add gitignore
- Automatically export media and model path (only works if gazebo is launched via the gazebo_ros package)
- Use `print(...)` and not `print ""`
- Use python3 `from tkinter import filedialog`

### CODE REVIEW

**Comment by Darkproduct** [comment]
I'll give up for now. This is an absolute mess. `noetic | passing` - in which world?

Here is a list of things that need to be fixed:
- Don't use `~/.gazebo/models`! Use the models directory from your package. (`scripts/model.py`)
- Use path in read and write file and don't change your directory path all the time. This is not bash. It's python... (see `create_model` function in `scripts/model.py`)
- How is this command `rosrun gazebo_terrain terrain_gen.sh` from the readme supposed to work? It calls `model.py "$MODEL_PATH" "$YOURIMAGENAME"` but `model.py` has no `main`.

Someone can use this PR as a starting point to fix this.

**Comment by Darkproduct** [comment]
The last commit addresses some of the issues. At least `main.py` is now working. 
How to use this branch:
```
# Generate a new model with
rosrun gazebo_terrain main.py

# Run this and insert the new model from the insert tab in gazebo
rosrun gazebo_ros gazebo

# This should work even without exporting the GAZEBO_MODEL_PATH
```

**Comment by MatthewVerbryke** [comment]
Sorry about this.
I recently merged some code from another contributor who was working with noetic and was in the middle of updating the entire program when I got distracted by some other work I needed to accomplish. I'm aware of the fact that it doesn't quite work with noetic or melodic at the moment and that several items need to be reworked, but I forgot to update the readme to indicate that this is a work in progress. 

I will update it now to prevent further confusion until I can work on this further.

**Comment by Darkproduct** [comment]
An readme update would be nice. You can merge this PR is you want, then the installation with `rosdep` will work on noetic and you can generate new models with `rosrun gazebo_terrain main.py`. See my last post.

**Pull request merged**
